version: '3'
services:
  guru-app:
    image: jdwilson2005/guru-app
    env_file:
      - ./project/config.prod.env
    ports:
      - 8080:8080
    networks:
      - app-network

  guru-ui:
    image: jdwilson2005/guru-ui
    restart: unless-stopped
    ports:
      - 80:80
    links:
      - guru-app
    networks:
      - app-network

networks:
  app-network:
    driver: bridge