version: '3'
services:
  guru-postgres:
    image: postgres:9.6-alpine
    container_name: guru-postgres
    volumes:
      - guru-dev-data:/var/lib/postgresql/data
    ports:
      - 5432:5432
    environment:
      - POSTGRES_DB=guru
      - POSTGRES_USER=guru
      - POSTGRES_PASSWORD=guru
    networks:
      - app-network

  guru-app:
    build: ./app
    container_name: guru-app
    env_file:
      - ./config.dev.env
    ports:
      - 8080:8080
    links:
      - guru-postgres
    networks:
      - app-network

  guru-ui:
    build: ./ui
    container_name: guru-ui
    restart: unless-stopped
    ports:
      - 80:80
    links:
      - guru-app
    networks:
      - app-network

volumes:
  guru-dev-data: 

networks:
  app-network:
    driver: bridge