version: '3'
services:
  guru-app:
    image: jdwilson2005/guru-app
    environment:
      - DB_SERVER=guru-postgres
      - POSTGRES_DB=guru
      - POSTGRES_USER=guru
      - POSTGRES_PASSWORD=guru
    ports:
      - 8080:8080

  guru-ui:
    image: jdwilson2005/guru-ui
    ports:
      - 80:80
    links:
      - guru-app