version: 2
jobs:
  build:
    working_directory: /home-cinema-guru
    docker:
      - image: docker:17.05.0-ce-git
    steps:
      - checkout
      - setup_remote_docker
      - run:
          name: Install Docker Compose
          command: |
            curl -L https://github.com/docker/compose/releases/download/1.25.3/docker-compose-`uname -s`-`uname -m` > ~/docker-compose
            chmod +x ~/docker-compose
            sudo mv ~/docker-compose /usr/local/bin/docker-compose
      # - run:
      #   name: Install dependencies
      #   command: | set -x curl -L https://github.com/docker/compose/releases/download/1.25.3/docker-compose-`uname -s`-`uname -m` > /usr/local/bin/docker-compose chmod +x /usr/local/bin/docker-compose
      - run:
        name: run tests
        command: |
          docker-compose up -d
          docker-compose run guru-app npm test
      - deploy:
        name: Push app Docker image
        command: |
          docker login -e $DOCKER_HUB_EMAIL -u $DOCKER_HUB_USER_ID -p $DOCKER_HUB_PWD
          docker tag home-cinema-guru_guru-ui $DOCKER_HUB_USER_ID/guru-ui:$CIRCLE_SHA1
          docker tag home-cinema-guru_guru-ui $DOCKER_HUB_USER_ID/guru-ui:latest
          docker tag home-cinema-guru_guru-app $DOCKER_HUB_USER_ID/guru-ui:$CIRCLE_SHA1
          docker tag home-cinema-guru_guru-app $DOCKER_HUB_USER_ID/guru-ui:latest
          docker push $DOCKER_HUB_USER_ID/guru-ui:$CIRCLE_SHA1
          docker push $DOCKER_HUB_USER_ID/guru-ui:latest
          docker push $DOCKER_HUB_USER_ID/guru-app:$CIRCLE_SHA1
          docker push $DOCKER_HUB_USER_ID/guru-app:latest