version: 2
jobs:
  build:
    filters:
      branches:
        only: master
    working_directory: /home-cinema-guru
    docker:
      - image: docker:17.05.0-ce-git
    steps:
      - checkout
      - setup_remote_docker
      - run:
          name: Install Docker Compose
          command: |
            apk add --no-cache py-pip=9.0.0-r1
            pip install docker-compose==1.15.0
      - run:
          name: run tests
          command: |
            docker-compose up -d
            docker-compose run guru-app npm test
      - deploy:
          name: Push app Docker image
          command: |
            docker login -e $DOCKER_HUB_EMAIL -u $DOCKER_HUB_USER_ID -p $DOCKER_HUB_PWD
            docker tag home-cinema-guru_guru-ui $DOCKER_HUB_USER_ID/guru-ui:$CIRCLE_SHA1
            docker tag home-cinema-guru_guru-ui $DOCKER_HUB_USER_ID/guru-ui:latest
            docker tag home-cinema-guru_guru-app $DOCKER_HUB_USER_ID/guru-app:$CIRCLE_SHA1
            docker tag home-cinema-guru_guru-app $DOCKER_HUB_USER_ID/guru-app:latest
            docker push $DOCKER_HUB_USER_ID/guru-ui:$CIRCLE_SHA1
            docker push $DOCKER_HUB_USER_ID/guru-ui:latest
            docker push $DOCKER_HUB_USER_ID/guru-app:$CIRCLE_SHA1
            docker push $DOCKER_HUB_USER_ID/guru-app:latest