version: 2
jobs:
  build:
    docker:
      - image: circleci/node:jessie
    steps:
      - checkout
      - setup_remote_docker
      - add_ssh_keys:
          fingerprints:
              - "a2:78:37:a3:68:c9:b7:f8:12:64:0e:b7:9b:b1:a2:d5"
      - run:
          name: run tests
          command: |
            docker-compose build
            docker-compose up -d
            docker-compose run guru-app npm test
            docker-compose logs
      - run:
          name: Push app Docker image
          command: |
            docker login --username $DOCKER_HUB_USER_ID --password $DOCKER_HUB_PWD
            docker tag project_guru-ui $DOCKER_HUB_USER_ID/guru-ui:$CIRCLE_SHA1
            docker tag project_guru-ui $DOCKER_HUB_USER_ID/guru-ui:latest
            docker tag project_guru-app $DOCKER_HUB_USER_ID/guru-app:$CIRCLE_SHA1
            docker tag project_guru-app $DOCKER_HUB_USER_ID/guru-app:latest
            docker push $DOCKER_HUB_USER_ID/guru-ui:$CIRCLE_SHA1
            docker push $DOCKER_HUB_USER_ID/guru-ui:latest
            docker push $DOCKER_HUB_USER_ID/guru-app:$CIRCLE_SHA1
            docker push $DOCKER_HUB_USER_ID/guru-app:latest
      - run:
          name: Deploy app to stage
          command: |
            scp docker-compose.prod.yml circleci@$GURU_STAGE_IP:./
